/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.CongregacaoDao;
import dao.MembroDao;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.Congregacao;
import modelo.Membro;
import util.ManipulaImagem;

/**
 *
 * @author Tony
 */
public class FrmCongregacaoCadastro extends javax.swing.JInternalFrame {

    private boolean novo;
    private int pastorResponsavel_id;
    MembroDao membroDao = new MembroDao();
    CongregacaoDao congregacaoDao = new CongregacaoDao();
    Membro membro;

    /**
     * Creates new form Frm_CadastroCongregacao
     */
    public FrmCongregacaoCadastro() {
        initComponents();
        txtCodigo.setVisible(false);
        habilitaCampos(false);
        carregaCompoPastor();
        carregaTabela();
        botaoInicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeIgreja = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        cboPastor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        grelhaIgrejas = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        janelaFoto = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Cadastro de Igrejas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome Igreja:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Endereço:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Bairro:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Cidade:");

        txtNomeIgreja.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtEndereco.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtBairro.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtCidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Cep:");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Pastor Responsável:");

        grelhaIgrejas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Pastor Responsável", "Bairro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grelhaIgrejas.setRowHeight(20);
        grelhaIgrejas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grelhaIgrejasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grelhaIgrejas);
        if (grelhaIgrejas.getColumnModel().getColumnCount() > 0) {
            grelhaIgrejas.getColumnModel().getColumn(0).setMinWidth(30);
            grelhaIgrejas.getColumnModel().getColumn(0).setPreferredWidth(30);
            grelhaIgrejas.getColumnModel().getColumn(0).setMaxWidth(30);
            grelhaIgrejas.getColumnModel().getColumn(1).setMinWidth(350);
            grelhaIgrejas.getColumnModel().getColumn(1).setPreferredWidth(350);
            grelhaIgrejas.getColumnModel().getColumn(1).setMaxWidth(350);
            grelhaIgrejas.getColumnModel().getColumn(2).setMinWidth(300);
            grelhaIgrejas.getColumnModel().getColumn(2).setPreferredWidth(300);
            grelhaIgrejas.getColumnModel().getColumn(2).setMaxWidth(300);
        }

        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/add_page.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/block.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/clear.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setPreferredSize(new java.awt.Dimension(103, 33));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ruler_pencil.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cross.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/disk-black.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Telefone:");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        janelaFoto.setBackground(new java.awt.Color(204, 204, 204));
        janelaFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        janelaFoto.setText("INSERIR LOGO");
        janelaFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        janelaFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                janelaFotoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNomeIgreja, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtTelefone)
                                        .addGap(18, 18, 18))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtCep, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(235, 235, 235))
                                            .addComponent(cboPastor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtEndereco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(janelaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNomeIgreja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboPastor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(janelaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNovo)
                        .addComponent(btnCancelar)
                        .addComponent(btnAlterar)
                        .addComponent(btnExcluir)
                        .addComponent(btnSalvar)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparTudo();
        novo = true;
        botaoInicio();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        novo = true;
        limparTudo();
        habilitaCampos(true);
        botaoNovo();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void grelhaIgrejasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grelhaIgrejasMouseClicked
        // TODO add your handling code here:

        int linha = (int) grelhaIgrejas.getValueAt(grelhaIgrejas.getSelectedRow(), 0);
        txtCodigo.setText(linha + "");

        Congregacao cong = congregacaoDao.getCongregacao(linha);
        txtNomeIgreja.setText(cong.getNomeCongregacao());
        cboPastor.setSelectedItem(cong.getPastor().getNome());
        txtTelefone.setText("");
        txtTelefone.setText(cong.getTelefone());
        txtEndereco.setText(cong.getEndereco());
        txtBairro.setText(cong.getBairro());
        txtCidade.setText(cong.getCidade());
        txtCep.setText("");
        txtCep.setText(cong.getCep());
        btnAlterar.setEnabled(true);
        if (grelhaIgrejas.getRowCount() > 1) {
            btnExcluir.setEnabled(true);
        }

        if (cong.getLogo() != null) {
            ManipulaImagem.exibirImagemNoLabel(cong.getLogo(), janelaFoto);
            janelaFoto.setText("");
        } else {
            janelaFoto.setIcon(new ImageIcon());
            janelaFoto.setText("SEM LOGO");
        }


    }//GEN-LAST:event_grelhaIgrejasMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        botaoCancelar();
        limparTudo();
        novo = true;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        botaoAlterar();
        habilitaCampos(true);
        novo = false;
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

        int resposta = JOptionPane.showConfirmDialog(this, "Deseja Excluir a congreação: " + txtNomeIgreja.getText());
        // 0 - SIM | 1 - NÃO | 2 - CANCELAR | -1 - FECHOU A TELA
        switch (resposta) {
            case 0:
                
                if (congregacaoDao.excluir(Integer.parseInt(txtCodigo.getText()))) {
                    carregaTabela();
                    JOptionPane.showMessageDialog(null, "Excluido com Sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Igreja não pode ser Excluída.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
                break;
            default:
                System.out.println(resposta);
                JOptionPane.showMessageDialog(null, "Operação Cancelada.", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (txtNomeIgreja.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome a Igreja não completa.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (cboPastor.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Pastor não informado.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtBairro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o bairro.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Congregacao congregacao = new Congregacao();
        congregacao.setNomeCongregacao(txtNomeIgreja.getText());
        int idPastor = membroDao.getIdMembro(cboPastor.getSelectedItem().toString());
        Membro m = new Membro(idPastor);
        congregacao.setPastor(m);
        congregacao.setTelefone(txtTelefone.getText());
        congregacao.setEndereco(txtEndereco.getText());
        congregacao.setBairro(txtBairro.getText());
        congregacao.setCidade(txtCidade.getText());
        congregacao.setCep(txtCep.getText());
        congregacao.setLogo(converteFotoParaBanco(janelaFoto));
        // SE FOR NOVO ---------------------------------------------------------
        if (novo) {
            if (congregacaoDao.inserirNovo(congregacao)) {
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar no banco.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            // ALTERAÇÃO -----------------------------------------------------------   
        } else {
            congregacao.setIdCongregacao(Integer.parseInt(txtCodigo.getText()));
            if (congregacaoDao.alterar(congregacao)) {
                JOptionPane.showMessageDialog(null, "Alterado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao altera no banco.", "Erro", JOptionPane.ERROR_MESSAGE);
            }

            carregaTabela();
            limparTudo();
            botaoInicio();
            habilitaCampos(false);
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void janelaFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_janelaFotoMouseClicked
        // TODO add your handling code here:
        //PEGA DUPLO CLIQUE
        int click;
        if (novo) {
            click = 1;
        } else {
            click = 2;
        }
        if (evt.getClickCount() == click) {
            String caminhaImagem;
            try {
                JFileChooser file = new JFileChooser();
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("Pasta de Seleção aberta.", "jpg", "png", "jpeg");
                file.addChoosableFileFilter(filtro);
                file.setAcceptAllFileFilterUsed(false);
                file.setDialogType(JFileChooser.OPEN_DIALOG);
                //file.showOpenDialog(this);

                if (file.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                    caminhaImagem = file.getSelectedFile().getPath();
                    ImageIcon icon = new ImageIcon(ManipulaImagem.setImagemDimensao(caminhaImagem, 150, 168));
                    janelaFoto.setIcon(icon);
                    janelaFoto.setText("");
                }
            } catch (HeadlessException e) {
                janelaFoto.setIcon(new ImageIcon());
                janelaFoto.setText("INSERIR LOGO");
            }        // T

        }
    }//GEN-LAST:event_janelaFotoMouseClicked

    // LIMPAR TUDO ////////////////////////////////////////////////////////////
    private void limparTudo() {
        txtCodigo.setText("");
        txtNomeIgreja.setText("");
        txtEndereco.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtCep.setText("");
        txtTelefone.setText("");
        cboPastor.setSelectedIndex(0);
        janelaFoto.setIcon(new ImageIcon());
        janelaFoto.setText("INSERIR LOGO");
    }

    // HABILITADO E DESABILITADO ///////////////////////////////////////////////
    private void habilitaCampos(boolean x) {
        txtCodigo.setEnabled(x);
        txtNomeIgreja.setEnabled(x);
        txtEndereco.setEnabled(x);
        txtBairro.setEnabled(x);
        txtTelefone.setEnabled(x);
        txtCidade.setEnabled(x);
        txtCep.setEnabled(x);
        cboPastor.setEnabled(x);
        grelhaIgrejas.setEnabled(!x);
    }

    // CARREGA PASTORES NA COMBOBOX ///////////////////////////////////////////
    private void carregaCompoPastor() {
        ArrayList<Membro> lista = membroDao.getListagem("");
        cboPastor.removeAllItems();
        cboPastor.addItem("Selecione...");
        for (Membro m : lista) {
            cboPastor.addItem(m.getNome());
        }

    }

    // CARREGA OS DADOS DA TABELA //////////////////////////////////////////////
    private void carregaTabela() {
        DefaultTableModel tabelaModelo = (DefaultTableModel) grelhaIgrejas.getModel();
        ArrayList<Congregacao> lista = congregacaoDao.getListaCongregacoes();
        tabelaModelo.setNumRows(0);
        for (int i = 0; i < lista.size(); i++) {
            tabelaModelo.addRow(new Object[]{
                lista.get(i).getIdCongregacao(),
                lista.get(i).getNomeCongregacao(),
                lista.get(i).getPastor().getNome(),
                lista.get(i).getBairro(),});
        }
    }

    // BOTAO INICIAL ///////////////////////////////////////////////////////////
    private void botaoInicio() {
        btnAlterar.setEnabled(!true);
        btnCancelar.setEnabled(true);
        //btnExcluir.setEnabled(!true);
        btnLimpar.setEnabled(true);
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(!true);

    }

    // BOTAO NOVO //////////////////////////////////////////////////////////////
    private void botaoNovo() {
        btnAlterar.setEnabled(!true);
        btnCancelar.setEnabled(true);
        //btnExcluir.setEnabled(!true);
        btnLimpar.setEnabled(true);
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(true);

    }

    // BOTAO ALTERAR ///////////////////////////////////////////////////////////
    private void botaoAlterar() {
        btnAlterar.setEnabled(!true);
        btnCancelar.setEnabled(true);
        //btnExcluir.setEnabled(!true);
        btnLimpar.setEnabled(true);
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(true);

    }

    // BOTAO CANCELAR //////////////////////////////////////////////////////////
    private void botaoCancelar() {
        botaoInicio();
    }

    // BOTAO EXCLUIR ///////////////////////////////////////////////////////////
    private void botaoExcluir() {
        botaoInicio();
    }

    // FUNÇÃO CONVERTE FOTO EM BITES //////////////////////////////////////////
    private byte[] converteFotoParaBanco(JLabel nomeLabelFoto) {

        Image img = ((ImageIcon) nomeLabelFoto.getIcon()).getImage();
        ByteArrayOutputStream buffer = null;
        byte[] fotoConvertida = null;

        if (img != null) {

            img = ((ImageIcon) nomeLabelFoto.getIcon()).getImage();
            BufferedImage bi = new BufferedImage(//é a imagem na memória e que pode ser alterada
                    img.getWidth(null),
                    img.getHeight(null),
                    BufferedImage.TYPE_INT_RGB);
            Graphics2D g2 = bi.createGraphics();
            g2.drawImage(img, 0, 0, null);
            buffer = new ByteArrayOutputStream();

            try {

                ImageIO.write(bi, "jpg", buffer);
                fotoConvertida = buffer.toByteArray();

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Erro não Conveter a image.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        //----FIM------INICIO DO TRATAMENTO DA FOTO-----------------------------
        return fotoConvertida;
    }

    ////////////////////////////////////////////////////////////////////////////
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboPastor;
    private javax.swing.JTable grelhaIgrejas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel janelaFoto;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNomeIgreja;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
