/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.DizimoDao;
import dao.MembroDao;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.table.DefaultTableModel;
import modelo.Dizimo;
import modelo.Membro;

/**
 *
 * @author Tony
 */
public class FrmDizimoConsulta extends javax.swing.JDialog {

    DefaultTableModel tabelaModelo;
    DizimoDao dizimoDao = new DizimoDao();
    MembroDao membroDao = new MembroDao();

    SimpleDateFormat sdfDiaMes = new SimpleDateFormat("dd/MM");

    /**
     * Creates new form Frm_UsuarioConsulta
     */
    public FrmDizimoConsulta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tabelaModelo = (DefaultTableModel) tabelaAniversarios.getModel();
        carregaTabela(0);
        carregaAno();
        anoAtual();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        grelhaPesquisaUsuario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblQuantidade = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAniversarios = new javax.swing.JTable();
        cboAno = new javax.swing.JComboBox<>();
        lblTotal = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        grelhaPesquisaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome:", "Cargo Igreja", "Data Congregação", "Dizimista", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grelhaPesquisaUsuario.setRowHeight(18);
        jScrollPane1.setViewportView(grelhaPesquisaUsuario);
        if (grelhaPesquisaUsuario.getColumnModel().getColumnCount() > 0) {
            grelhaPesquisaUsuario.getColumnModel().getColumn(0).setMaxWidth(50);
            grelhaPesquisaUsuario.getColumnModel().getColumn(1).setMinWidth(300);
            grelhaPesquisaUsuario.getColumnModel().getColumn(1).setPreferredWidth(300);
            grelhaPesquisaUsuario.getColumnModel().getColumn(1).setMaxWidth(300);
            grelhaPesquisaUsuario.getColumnModel().getColumn(2).setMinWidth(150);
            grelhaPesquisaUsuario.getColumnModel().getColumn(2).setPreferredWidth(150);
            grelhaPesquisaUsuario.getColumnModel().getColumn(2).setMaxWidth(150);
            grelhaPesquisaUsuario.getColumnModel().getColumn(3).setMinWidth(150);
            grelhaPesquisaUsuario.getColumnModel().getColumn(3).setPreferredWidth(100);
            grelhaPesquisaUsuario.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Consulta Dizimistas");

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel2.setText("Pesquisa por Nome:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/clear.png"))); // NOI18N
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblQuantidade.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lblQuantidade.setForeground(new java.awt.Color(102, 0, 0));
        lblQuantidade.setText("0 registros localizados.");

        tabelaAniversarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "JAN", "FEV", "MAR", "ABR", "MAI", "JUN", "JUL", "AGO", "SET", "OUT", "NOV", "DEZ", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAniversarios.setRowHeight(20);
        jScrollPane2.setViewportView(tabelaAniversarios);
        if (tabelaAniversarios.getColumnModel().getColumnCount() > 0) {
            tabelaAniversarios.getColumnModel().getColumn(0).setMinWidth(30);
            tabelaAniversarios.getColumnModel().getColumn(0).setPreferredWidth(15);
            tabelaAniversarios.getColumnModel().getColumn(0).setMaxWidth(30);
            tabelaAniversarios.getColumnModel().getColumn(2).setPreferredWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(2).setMaxWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(3).setPreferredWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(3).setMaxWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(4).setPreferredWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(4).setMaxWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(5).setPreferredWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(5).setMaxWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(6).setPreferredWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(6).setMaxWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(7).setPreferredWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(7).setMaxWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(8).setMinWidth(80);
            tabelaAniversarios.getColumnModel().getColumn(8).setPreferredWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(8).setMaxWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(9).setMinWidth(80);
            tabelaAniversarios.getColumnModel().getColumn(9).setPreferredWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(9).setMaxWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(10).setMinWidth(80);
            tabelaAniversarios.getColumnModel().getColumn(10).setPreferredWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(10).setMaxWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(11).setMinWidth(80);
            tabelaAniversarios.getColumnModel().getColumn(11).setPreferredWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(11).setMaxWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(12).setMinWidth(80);
            tabelaAniversarios.getColumnModel().getColumn(12).setPreferredWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(12).setMaxWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(13).setMinWidth(80);
            tabelaAniversarios.getColumnModel().getColumn(13).setPreferredWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(13).setMaxWidth(70);
            tabelaAniversarios.getColumnModel().getColumn(14).setMinWidth(100);
            tabelaAniversarios.getColumnModel().getColumn(14).setPreferredWidth(100);
            tabelaAniversarios.getColumnModel().getColumn(14).setMaxWidth(100);
        }

        cboAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAnoActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 87, 18));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("Total: R$ 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuantidade)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboAno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuantidade)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // TODO add your handling code here:
      int ano = Integer.parseInt(cboAno.getSelectedItem().toString());
        carregaTabela(ano);
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void cboAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAnoActionPerformed
        // TODO add your handling code here:

        carregaTabela(0);
    }//GEN-LAST:event_cboAnoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtPesquisa.setText("");
        mostraAnoCombo();
        carregaTabela(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    // CARREGA COMBOX
    private void mostraAnoCombo() {
        int ano = new Date().getYear();
        cboAno.setSelectedItem(ano);
    }

    // CARREA ANO NA COMBOBOX //////////////////////////////////////////////////
    private void carregaAno() {
        int ano = 2021;
        do {
            cboAno.addItem(ano + "");
            ano++;
        } while (ano < 2030);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDizimoConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDizimoConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDizimoConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDizimoConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDizimoConsulta dialog = new FrmDizimoConsulta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // MARCA O ANO ATUAL
    // CARREGA O MES ATUAL NA COMBOBOX /////////////////////////////////////////
    // CARREGA ANO ATUAL NA COMBOBOX ///////////////////////////////////////
    private void anoAtual() {
        int ano = new Date().getYear();
        cboAno.setSelectedItem(ano);

    }

    //FUNÇÃO QUE CARREAGO OS AS TABELAS
    private void carregaTabela(int ano) {
        int ano1 = ano;
        if(ano1 ==0){
            ano1 = 2021;
        }
        float totalMembro = 0;
        float totalGeral = 0;
        tabelaModelo.setNumRows(0);
        ArrayList<Membro> membros = membroDao.getListagem(txtPesquisa.getText());

        for (int i = 0; i < membros.size(); i++) {
            int codigoMembro = membros.get(i).getIdMembro();
            String vJAN = "", vFEV = "", vMAR = "", vABR = "", vMAI = "", vJUN = "", vJUL = "", vAGO = "", vSET = "",
                    vOUT = "", vNOV = "", vDEZ = "", vTOTAL;        
            ArrayList<Dizimo> lista = dizimoDao.getListaDizimosIDeAno(codigoMembro, ano1);
            for (int j = 0; j < lista.size(); j++) {
                String mesProcurado = lista.get(j).getMes();
                mesProcurado = mesProcurado.substring(0, 3);

                totalGeral = totalGeral + lista.get(j).getValor();
                totalMembro = totalMembro + lista.get(j).getValor();

                switch (mesProcurado) {
                    case "JAN":
                        vJAN = NumberFormat.getCurrencyInstance().format(lista.get(j).getValor());
                        break;
                    case "FEV":
                        vFEV = NumberFormat.getCurrencyInstance().format(lista.get(j).getValor());
                        break;
                    case "MAR":
                        vMAR = NumberFormat.getCurrencyInstance().format(lista.get(j).getValor());
                        break;
                    case "ABR":
                        vABR = NumberFormat.getCurrencyInstance().format(lista.get(j).getValor());
                        break;
                    case "MAI":
                        vMAI = NumberFormat.getCurrencyInstance().format(lista.get(j).getValor());
                        break;
                    case "JUN":
                        vJUN = NumberFormat.getCurrencyInstance().format(lista.get(j).getValor());
                        break;
                    case "JUL":
                        vJUL = NumberFormat.getCurrencyInstance().format(lista.get(j).getValor());
                        break;
                    case "AGO":
                        vAGO = NumberFormat.getCurrencyInstance().format(lista.get(j).getValor());
                        break;
                    case "SET":
                        vSET = NumberFormat.getCurrencyInstance().format(lista.get(j).getValor());
                        break;
                    case "OUT":
                        vOUT = NumberFormat.getCurrencyInstance().format(lista.get(j).getValor());
                        break;
                    case "NOV":
                        vNOV = NumberFormat.getCurrencyInstance().format(lista.get(j).getValor());
                        break;
                    case "DEZ":
                        vDEZ = NumberFormat.getCurrencyInstance().format(lista.get(j).getValor());
                        break;

                }

            }

            vTOTAL = NumberFormat.getCurrencyInstance().format(totalMembro);
            tabelaModelo.addRow(new Object[]{
                membros.get(i).getIdMembro(), membros.get(i).getNome(), vJAN, vFEV, vMAR, vABR, vMAI, vJUN, vJUL, vAGO, vSET, vOUT, vNOV, vDEZ, vTOTAL,});
            totalMembro = 0;
        }
        String totalFormatada = NumberFormat.getCurrencyInstance().format(totalGeral);
        lblTotal.setText("Total: " + totalFormatada);
        lblQuantidade.setText(tabelaModelo.getRowCount() + " Membros localizados.");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboAno;
    private javax.swing.JTable grelhaPesquisaUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tabelaAniversarios;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

    //FUNÇÃO PRIVADAS DO MEU FORMULARIO
    private int codigoUsuario;
    private boolean alterar;

    /**
     * @return the codigoUsuario
     */
    public int getCodigoUsuario() {
        return codigoUsuario;
    }

    /**
     * @param codigoUsuario the codigoUsuario to set
     */
    public void setCodigoUsuario(int codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
    }

    /**
     * @return the alterar
     */
    public boolean isAlterar() {
        return alterar;
    }

    /**
     * @param alterar the alterar to set
     */
    public void setAlterar(boolean alterar) {
        this.alterar = alterar;
    }

}
