/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.DizimoDao;
import dao.MembroDao;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Dizimo;
import modelo.Membro;

/**
 *
 * @author Tony
 */
public class FrmDizimoCadastro extends javax.swing.JFrame {

    // VARIAVEIS DO  PROJETO ---------------------------------------------------
    boolean novo;
    int membro_id;
    DizimoDao dizimoDao = new DizimoDao();
    MembroDao membroDao = new MembroDao();
    DefaultTableModel modeloTabela;

    // FIM - VARIAVEIS DO  PROJETO ---------------------------------------------
    /**
     * Creates new form FrmDizimoCadastro
     */
    public FrmDizimoCadastro() {
        initComponents();
        carregaAno();
        dataHoje();
        anoAtual();
        mostraMesCombo();
        carregaComboboxNome();
        txtValor.setText("R$ ");
        modeloTabela = (DefaultTableModel) tabelaDizimo.getModel();
        novo = true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ckAtivo = new javax.swing.JRadioButton();
        cboNome = new componentes.UJComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtData = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        cboMes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboAno = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRecibo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cboFormaPagamento = new javax.swing.JComboBox<>();
        ckInativo = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDizimo = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Nome:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Cadastro de Dízimo");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ckAtivo.setBackground(java.awt.Color.white);
        buttonGroup1.add(ckAtivo);
        ckAtivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckAtivo.setText("Ativo");

        cboNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNomeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Data:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Mês:");

        cboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JANEIRO", "FEVEREIRO", "MARÇO", "ABRIL", "MAIO", "JUNHO", "JULHO", "AGOSTO", "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO" }));
        cboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Ano:");

        cboAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAnoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Forma de Pagamento:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Recibo:");

        txtRecibo.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Situação:");

        btnSalvar.setBackground(new java.awt.Color(0, 102, 51));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/disk-black.png"))); // NOI18N
        btnSalvar.setText("   SALVAR");
        btnSalvar.setOpaque(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/trigo.png"))); // NOI18N

        txtValor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Valor:");

        cboFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DINHEIRO", "CHEQUE", "CARTÃO DEBITO", "CARTÃO CRÉDITO", "DEPÓSITO", "TRANSFERÊNCIA BANCÁRIA", "TRANSFERÊNCIA PELO CELULAR" }));

        ckInativo.setBackground(java.awt.Color.white);
        buttonGroup1.add(ckInativo);
        ckInativo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ckInativo.setText("Inativo");

        tabelaDizimo.setAutoCreateRowSorter(true);
        tabelaDizimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Mes", "Valor"
            }
        ));
        tabelaDizimo.setRowHeight(20);
        jScrollPane2.setViewportView(tabelaDizimo);
        if (tabelaDizimo.getColumnModel().getColumnCount() > 0) {
            tabelaDizimo.getColumnModel().getColumn(0).setPreferredWidth(60);
            tabelaDizimo.getColumnModel().getColumn(0).setMaxWidth(60);
            tabelaDizimo.getColumnModel().getColumn(1).setPreferredWidth(300);
            tabelaDizimo.getColumnModel().getColumn(1).setMaxWidth(300);
        }

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Novo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel8)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(ckAtivo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ckInativo))
                                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(cboFormaPagamento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cboAno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(cboNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ckAtivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ckInativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboMesActionPerformed

    private void cboAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAnoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        String valorNovo = txtValor.getText().replace("R$ ", "").replace(",", "-").replace(".", "").replace("-", ".").replace("R$", "");

        if (cboNome.getSelectedItem().equals("Selecione...")) {
            JOptionPane.showMessageDialog(this, "Informe o nome do Membro.", "ERRO", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtData.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe uma data válida.", "ERRO", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (valorNovo.equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(this, "Valor não foi informado.", "ERRO", JOptionPane.ERROR_MESSAGE);
            txtValor.requestFocus();
            return;
        }
        membro_id = membroDao.getIdMembro(cboNome.getSelectedItem().toString());

        if (dizimoDao.verificaSeJaPagou(membro_id, cboMes.getSelectedItem().toString()) > 0 && novo) {
            JOptionPane.showMessageDialog(this, "Consta dizimo cadastrado esta Mês, verifique.", "ERRO", JOptionPane.ERROR_MESSAGE);
            txtValor.requestFocus();
            return;
        }
    

        //membro_id = membroDao.getIdMembro(cboNome.getSelectedItem().toString());
        Dizimo dizimo = new Dizimo();
        dizimo.setDataCadastro(txtData.getDate());
        Membro m = new Membro(membro_id);
        dizimo.setMembro(m);
        dizimo.setMes(cboMes.getSelectedItem().toString());
        dizimo.setAno(Integer.parseInt(cboAno.getSelectedItem().toString()));
        dizimo.setFormaPaga(cboFormaPagamento.getSelectedItem().toString());
        dizimo.setValor(Float.parseFloat(valorNovo));
        if (novo) {
            if (dizimoDao.inserirNovo(dizimo)) {
                JOptionPane.showMessageDialog(this, "Dízimo cadastrado com sucesso !", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                limpar();
            } else {

                JOptionPane.showMessageDialog(this, "Erro ao cadastrar dízimo.", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            dizimo.setIdDizimo(Integer.parseInt(txtRecibo.getText()));
            if (dizimoDao.alterar(dizimo)) {
                JOptionPane.showMessageDialog(this, "Dízimo alterado com sucesso !", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                limpar();
            } else {

                JOptionPane.showMessageDialog(this, "Erro ao alterar dízimo.", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        // TODO add your handling code here:
        String testeDigitado = txtValor.getText().replace("R$", "").replace(",", ".");
        Double valor;

        try {
            valor = Double.parseDouble(testeDigitado);
            System.out.println(valor);
        } catch (Exception e) {
            System.out.println("não é numero" + e);
            txtValor.setText("R$ ");
        }
    }//GEN-LAST:event_txtValorKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmMembroConsultaRapida f = new FrmMembroConsultaRapida(this, true);
        f.setVisible(true);
        if (f.getCodigo() > 0) {
            cboNome.setSelectedItem(f.getName());
            membro_id = f.getCodigo();
            txtValor.requestFocus();
            try {
                if (f.getStatus().equalsIgnoreCase("ATIVO")) {
                    ckAtivo.setSelected(true);
                } else {
                    ckInativo.setSelected(true);
                }

            } catch (Exception e) {
                ckInativo.setSelected(true);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNomeActionPerformed
        // TODO add your handling code here:
        try {
            Membro m = membroDao.getMembroPorNome(cboNome.getSelectedItem().toString());
            ArrayList<Dizimo> lista = new DizimoDao().getListaDizimosIDeAno(m.getIdMembro(), 2021);
            modeloTabela.setNumRows(0);
            if (lista.size() > 0) {
                for (Dizimo dizimo : lista) {
                    modeloTabela.addRow(new Object[]{dizimo.getIdDizimo(),
                        dizimo.getMembro().getNome(),
                        dizimo.getMes(),
                        NumberFormat.getCurrencyInstance().format(dizimo.getValor()),});
                }

            }

            if (m.getStatus().equalsIgnoreCase("ATIVO")) {
                ckAtivo.setSelected(true);
            } else {
                ckInativo.setSelected(true);
            }
            txtValor.requestFocus();

        } catch (Exception e) {
            ckInativo.setSelected(true);
        }

    }//GEN-LAST:event_cboNomeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        novo = true;
        limpar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (tabelaDizimo.getSelectedRow() >= 0) {
            int linha = tabelaDizimo.getSelectedRow();
            int codigo = (int) tabelaDizimo.getValueAt(linha, 0);
            // fim verifica se pede ser instalado
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o usuário", "confirm", JOptionPane.INFORMATION_MESSAGE);
            if (resposta == 0) {

                if (dizimoDao.excluir(codigo)) {
                    limpar();
                    modeloTabela.setNumRows(0);
                    JOptionPane.showMessageDialog(this, "Dízimo Excluido com sucesso.", "Sucesso", JOptionPane.WARNING_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao Excluir Dízimo.", "erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Dízimo não foi excluido", "erro", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (tabelaDizimo.getSelectedRow() >= 0) {
            int linha = tabelaDizimo.getSelectedRow();
            int codigo = (int) tabelaDizimo.getValueAt(linha, 0);
            Dizimo dizimo = dizimoDao.getDizimo(codigo);
            txtRecibo.setText(dizimo.getIdDizimo()+"");
            txtData.setDate(dizimo.getDataCadastro());
            cboNome.setSelectedItem(dizimo.getMembro().getNome());
            cboMes.setSelectedItem(dizimo.getMes());
            cboAno.setSelectedItem(dizimo.getAno());
            cboFormaPagamento.setSelectedItem(dizimo.getFormaPaga());
            txtValor.setText(NumberFormat.getCurrencyInstance().format(dizimo.getValor()));
            novo = false;
            
         }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDizimoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDizimoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDizimoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDizimoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDizimoCadastro().setVisible(true);
            }
        });
    }

    // CARREA NOMES NA COMBOBOX //////////////////////////////////////////////////
    private void carregaComboboxNome() {
        ArrayList<Membro> lista = membroDao.getListagem("");
        cboNome.addItem("Selecione...");
        for (int i = 0; i < lista.size(); i++) {
            cboNome.addItem(lista.get(i).getNome());
        }

    }

    // CARREA ANO NA COMBOBOX //////////////////////////////////////////////////
    private void carregaAno() {
        int ano = 2021;
        do {
            cboAno.addItem(ano + "");
            ano++;
        } while (ano < 2030);

    }

    // CARREGA DATA  ///////////////////////////////////////////////////////////
    private void dataHoje() {

        Date data = new Date();
        txtData.setDate(data);

    }

    // CARREGA ANO ATUAL NA COMBOBOX ///////////////////////////////////////
    private void anoAtual() {
        int ano = new Date().getYear();
        cboAno.setSelectedItem(ano);

    }

    // CARREGA O MES ATUAL NA COMBOBOX /////////////////////////////////////////
    private void mostraMesCombo() {
        int mes2 = new Date().getMonth();
        cboMes.setSelectedIndex(mes2);
    }

    //LIMPA OS CAMPOS //////////////////////////////////////////////////////////
    private void limpar() {
        txtRecibo.setText("");
        cboNome.setSelectedIndex(0);
        cboFormaPagamento.setSelectedIndex(0);
        txtValor.setText("R$ ");
        anoAtual();
        dataHoje();
        mostraMesCombo();
        ckAtivo.setSelected(false);
        modeloTabela.setNumRows(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboAno;
    private javax.swing.JComboBox<String> cboFormaPagamento;
    private javax.swing.JComboBox<String> cboMes;
    private componentes.UJComboBox cboNome;
    private javax.swing.JRadioButton ckAtivo;
    private javax.swing.JRadioButton ckInativo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelaDizimo;
    private com.toedter.calendar.JDateChooser txtData;
    private javax.swing.JTextField txtRecibo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
