/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.UsuarioDao;
import javax.swing.JOptionPane;
import modelo.Usuario;
import util.ConvertendoSenhaMD5;
import util.Datas;

/**
 *
 * @author Tony
 */
public class FrmUsuarioCadastro extends javax.swing.JInternalFrame {

    UsuarioDao usuarioDao = new UsuarioDao();
    Usuario usuario;
    public boolean novo;

    public FrmUsuarioCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtConfirmaSenha = new javax.swing.JPasswordField();
        cboPrevilegio = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cboStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Cadatro de Usuario");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel1.setText("Código:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 69, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 69, -1, -1));

        txtCodigo.setEnabled(false);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 90, 49, -1));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 90, 356, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel3.setText("Login:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel4.setText("Senha:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 137, 166, -1));
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 137, 122, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel5.setText("Confirma Senha:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));
        jPanel1.add(txtConfirmaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 137, 111, -1));

        cboPrevilegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Administrador", "Usuário" }));
        jPanel1.add(cboPrevilegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 184, 294, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel6.setText("Previlégio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 170, 100, -1));

        cboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        jPanel1.add(cboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 184, 111, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel7.setText("Status:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 94, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel8.setText("Cadastro de usuários do sistema");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 29, 468, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo-pequeno.png"))); // NOI18N
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 69, 153, 144));

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/disk-black.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 219, 127, -1));

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/zoom.png"))); // NOI18N
        btnPesquisa.setText("PESQUISAR");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 219, 127, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:
        FrmUsuarioConsulta f = new FrmUsuarioConsulta(null, true);
        f.setAlterar(true);
        f.setVisible(true);
        int idRetornado = f.getCodigoUsuario();
        if (idRetornado > 0) {
            usuario = usuarioDao.getUsuario(idRetornado);
            limpar();
            txtCodigo.setText(String.valueOf(usuario.getIdUsuario()));
            txtNome.setText(usuario.getNome());
            txtLogin.setText(usuario.getLogin());
            cboPrevilegio.setSelectedItem(usuario.getPrevilegio());
            cboStatus.setSelectedItem(usuario.getStatus());
            novo = false;
        }

    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        // verifica se é alteação =============================================
        novo = txtCodigo.getText().equals("");
        // valida os campos ===================================================
        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome não informado", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtLogin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Login não informado", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Senha não informado", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtConfirmaSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Confirmação de senha inválida", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!txtConfirmaSenha.getText().equals(txtSenha.getText())) {
            JOptionPane.showMessageDialog(this, "Senhas não são iguais.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (cboPrevilegio.getSelectedItem().equals("Selecione...")) {
            JOptionPane.showMessageDialog(this, " Previlègio não informado.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // seta valores no usuario /////////////////////////////////////////////
        usuario = new Usuario();
        usuario.setNome(txtNome.getText());
        usuario.setLogin(txtLogin.getText());
        usuario.setSenha(ConvertendoSenhaMD5.convertendoSenha(txtSenha.getText()));
        usuario.setPrevilegio(cboPrevilegio.getSelectedItem().toString());
        usuario.setStatus(cboStatus.getSelectedItem().toString());
        usuario.setDataCadastro(Datas.getData());
        //VERIFICA SE ALTEARAÇÃO
        if (novo) {
            //inserindo novo no banco
           if(usuarioDao.inserirNovo(usuario)){
               JOptionPane.showMessageDialog(this, "Cadastrado com Sucesso.", "Erro", JOptionPane.INFORMATION_MESSAGE);
               limpar();
           }else{
              JOptionPane.showMessageDialog(this, " Erro ao cadastrar usuário.", "Erro", JOptionPane.ERROR_MESSAGE); 
           }
        } else {
            //alterando no banco
            usuario.setIdUsuario(Integer.parseInt(txtCodigo.getText()));
            if(usuarioDao.alterar(usuario)){
                JOptionPane.showMessageDialog(this, "Alterado com Sucesso.", "Erro", JOptionPane.INFORMATION_MESSAGE);
                limpar();
            }else{
                JOptionPane.showMessageDialog(this, " Erro ao alterar usuário.", "Erro", JOptionPane.ERROR_MESSAGE); 
            }

        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    //FUNÇÃO LIMPAR CAMPOS
    private void limpar() {
        txtCodigo.setText("");
        txtNome.setText("");
        txtLogin.setText("");
        txtSenha.setText("");
        txtConfirmaSenha.setText("");
        cboPrevilegio.setSelectedIndex(0);
        cboStatus.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboPrevilegio;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtConfirmaSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
